=== BulkSecurityGeneratorProject/myhealth/myhealth-web/app/reference-data/PercentileReferenceData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="unit">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="cm"/>
				<xs:enumeration value="kg"/>
				<xs:enumeration value="kg/m2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="HEIGHT"/>
				<xs:enumeration value="WEIGHT"/>
				<xs:enumeration value="HEAD CIRCUMFERENCE"/>
				<xs:enumeration value="BODY MASS INDEX"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="source">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="WHO"/>
				<xs:enumeration value="CDC"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="referenceData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="percentile" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="percentile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="displayValue" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="minAge">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="300"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="maxAge">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="300"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="300"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="age" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="300"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="gender">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FEMALE"/>
				<xs:enumeration value="MALE"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="code">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ageUnit">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="months"/>
				<xs:enumeration value="years"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PercentileReferenceData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="code"/>
				<xs:element ref="source"/>
				<xs:element ref="gender"/>
				<xs:element ref="type"/>
				<xs:element ref="unit"/>
				<xs:element ref="minAge"/>
				<xs:element ref="maxAge"/>
				<xs:element ref="ageUnit"/>
				<xs:element ref="title"/>
				<xs:element ref="referenceData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BulkSecurityGeneratorProject/myhealth/myhealth-web/app/reference-data/CDCMaleBMI2-20.xml
<!--Reference data is being taken from http://www.who.int/childgrowth/standards/en/ website-->
<!--Reference data used is retrieved from the table version of the percentile information-->
<PercentileReferenceData xsl:noNamespaceSchemaLocation="PercentileReferenceData.xsd" xmlns:xsl="http://www.w3.org/2001/XMLSchema-instance">
	<code>Percentile Reference Data</code>
	<source>CDC</source>
	<gender>MALE</gender>
	<type>BODY MASS INDEX</type>
	<unit>kg/m2</unit>
	<minAge>24</minAge>
	<maxAge>240</maxAge>
	<ageUnit>months</ageUnit>
	<title>CDC Boys 2-20 years Body Mass Index</title>
	<referenceData>
		<percentile displayValue="3rd" value="3">
			<item value="14.503476669" age="24"/>
			<item value="14.46882381" age="25"/>
			<item value="14.43459737" age="26"/>
			<item value="14.400828277" age="27"/>
			<item value="14.367547175" age="28"/>
			<item value="14.334784135" age="29"/>
			<item value="14.302568372" age="30"/>
			<item value="14.270928334" age="31"/>
			<item value="14.239889707" age="32"/>
			<item value="14.209478199" age="33"/>
			<item value="14.179716981" age="34"/>
			<item value="14.150627151" age="35"/>
			<item value="14.122227569" age="36"/>
			<item value="14.094534131" age="37"/>
			<item value="14.067563285" age="38"/>
			<item value="14.041322876" age="39"/>
			<item value="14.015824303" age="40"/>
			<item value="13.991073321" age="41"/>
			<item value="13.967074386" age="42"/>
			<item value="13.943826979" age="43"/>
			<item value="13.921331901" age="44"/>
			<item value="13.899586603" age="45"/>
			<item value="13.878583524" age="46"/>
			<item value="13.858315818" age="47"/>
			<item value="13.838774042" age="48"/>
			<item value="13.819947109" age="49"/>
			<item value="13.80182253" age="50"/>
			<item value="13.784386668" age="51"/>
			<item value="13.767626047" age="52"/>
			<item value="13.751522482" age="53"/>
			<item value="13.73606368" age="54"/>
			<item value="13.721233222" age="55"/>
			<item value="13.707015988" age="56"/>
			<item value="13.693397391" age="57"/>
			<item value="13.680362417" age="58"/>
			<item value="13.667899624" age="59"/>
			<item value="13.655996831" age="60"/>
			<item value="13.644643533" age="61"/>
			<item value="13.633830562" age="62"/>
			<item value="13.623549065" age="63"/>
			<item value="13.613794519" age="64"/>
			<item value="13.604561063" age="65"/>
			<item value="13.595844997" age="66"/>
			<item value="13.587643874" age="67"/>
			<item value="13.579956424" age="68"/>
			<item value="13.572782447" age="69"/>
			<item value="13.566122717" age="70"/>
			<item value="13.559978867" age="71"/>
			<item value="13.554353286" age="72"/>
			<item value="13.549249014" age="73"/>
			<item value="13.544669635" age="74"/>
			<item value="13.540618386" age="75"/>
			<item value="13.537100973" age="76"/>
			<item value="13.534121468" age="77"/>
			<item value="13.531684723" age="78"/>
			<item value="13.529795725" age="79"/>
			<item value="13.528459943" age="80"/>
			<item value="13.527681304" age="81"/>
			<item value="13.527465647" age="82"/>
			<item value="13.527817944" age="83"/>
			<item value="13.52874305" age="84"/>
			<item value="13.530245676" age="85"/>
			<item value="13.532330364" age="86"/>
			<item value="13.535001468" age="87"/>
			<item value="13.538263144" age="88"/>
			<item value="13.542119379" age="89"/>
			<item value="13.546573748" age="90"/>
			<item value="13.551629882" age="91"/>
			<item value="13.557290983" age="92"/>
			<item value="13.563560058" age="93"/>
			<item value="13.570439865" age="94"/>
			<item value="13.577932909" age="95"/>
			<item value="13.586041435" age="96"/>
			<item value="13.594767424" age="97"/>
			<item value="13.604112456" age="98"/>
			<item value="13.614078441" age="99"/>
			<item value="13.624666113" age="100"/>
			<item value="13.635876526" age="101"/>
			<item value="13.64771054" age="102"/>
			<item value="13.660168532" age="103"/>
			<item value="13.673250382" age="104"/>
			<item value="13.686956839" age="105"/>
			<item value="13.701287124" age="106"/>
			<item value="13.716241034" age="107"/>
			<item value="13.731816758" age="108"/>
			<item value="13.748014703" age="109"/>
			<item value="13.764833246" age="110"/>
			<item value="13.782270842" age="111"/>
			<item value="13.800325929" age="112"/>
			<item value="13.818996662" age="113"/>
			<item value="13.838280984" age="114"/>
			<item value="13.85817663" age="115"/>
			<item value="13.878681126" age="116"/>
			<item value="13.899791796" age="117"/>
			<item value="13.921505762" age="118"/>
			<item value="13.94381995" age="119"/>
			<item value="13.966731092" age="120"/>
			<item value="13.990235806" age="121"/>
			<item value="14.014330207" age="122"/>
			<item value="14.039010696" age="123"/>
			<item value="14.064273173" age="124"/>
			<item value="14.090113438" age="125"/>
			<item value="14.116527107" age="126"/>
			<item value="14.143509617" age="127"/>
			<item value="14.171056231" age="128"/>
			<item value="14.199162032" age="129"/>
			<item value="14.227821931" age="130"/>
			<item value="14.257030662" age="131"/>
			<item value="14.286782789" age="132"/>
			<item value="14.317072705" age="133"/>
			<item value="14.347894631" age="134"/>
			<item value="14.379242621" age="135"/>
			<item value="14.411109333" age="136"/>
			<item value="14.443490382" age="137"/>
			<item value="14.476378606" age="138"/>
			<item value="14.509767412" age="139"/>
			<item value="14.543650049" age="140"/>
			<item value="14.57801961" age="141"/>
			<item value="14.612869033" age="142"/>
			<item value="14.648191101" age="143"/>
			<item value="14.683978443" age="144"/>
			<item value="14.72022354" age="145"/>
			<item value="14.75691872" age="146"/>
			<item value="14.794056164" age="147"/>
			<item value="14.831627905" age="148"/>
			<item value="14.869625831" age="149"/>
			<item value="14.908041684" age="150"/>
			<item value="14.946867065" age="151"/>
			<item value="14.986093432" age="152"/>
			<item value="15.025712104" age="153"/>
			<item value="15.065714261" age="154"/>
			<item value="15.106090947" age="155"/>
			<item value="15.146833068" age="156"/>
			<item value="15.1879314" age="157"/>
			<item value="15.229376584" age="158"/>
			<item value="15.271159134" age="159"/>
			<item value="15.313269432" age="160"/>
			<item value="15.355697735" age="161"/>
			<item value="15.398434176" age="162"/>
			<item value="15.441468765" age="163"/>
			<item value="15.484791389" age="164"/>
			<item value="15.52839182" age="165"/>
			<item value="15.572259709" age="166"/>
			<item value="15.616384596" age="167"/>
			<item value="15.660755908" age="168"/>
			<item value="15.70536296" age="169"/>
			<item value="15.750194963" age="170"/>
			<item value="15.795241019" age="171"/>
			<item value="15.840490131" age="172"/>
			<item value="15.885931199" age="173"/>
			<item value="15.931553027" age="174"/>
			<item value="15.977344323" age="175"/>
			<item value="16.023293705" age="176"/>
			<item value="16.069389698" age="177"/>
			<item value="16.115620744" age="178"/>
			<item value="16.161975197" age="179"/>
			<item value="16.208441335" age="180"/>
			<item value="16.255007353" age="181"/>
			<item value="16.301661372" age="182"/>
			<item value="16.348391441" age="183"/>
			<item value="16.395185538" age="184"/>
			<item value="16.442031574" age="185"/>
			<item value="16.488917395" age="186"/>
			<item value="16.535830787" age="187"/>
			<item value="16.582759472" age="188"/>
			<item value="16.62969112" age="189"/>
			<item value="16.67661334" age="190"/>
			<item value="16.723513693" age="191"/>
			<item value="16.770379686" age="192"/>
			<item value="16.817198778" age="193"/>
			<item value="16.863958377" age="194"/>
			<item value="16.910646682" age="195"/>
			<item value="16.957249256" age="196"/>
			<item value="17.003754296" age="197"/>
			<item value="17.050149023" age="198"/>
			<item value="17.096420616" age="199"/>
			<item value="17.142556204" age="200"/>
			<item value="17.188542869" age="201"/>
			<item value="17.234367642" age="202"/>
			<item value="17.280017501" age="203"/>
			<item value="17.325479371" age="204"/>
			<item value="17.370740117" age="205"/>
			<item value="17.415786538" age="206"/>
			<item value="17.46060537" age="207"/>
			<item value="17.505183272" age="208"/>
			<item value="17.549506825" age="209"/>
			<item value="17.593562522" age="210"/>
			<item value="17.637336764" age="211"/>
			<item value="17.680815846" age="212"/>
			<item value="17.723985953" age="213"/>
			<item value="17.766833147" age="214"/>
			<item value="17.809343234" age="215"/>
			<item value="17.851502186" age="216"/>
			<item value="17.893294718" age="217"/>
			<item value="17.934708987" age="218"/>
			<item value="17.975728091" age="219"/>
			<item value="18.01633608" age="220"/>
			<item value="18.056519892" age="221"/>
			<item value="18.09626344" age="222"/>
			<item value="18.135551117" age="223"/>
			<item value="18.174367057" age="224"/>
			<item value="18.212695116" age="225"/>
			<item value="18.250518862" age="226"/>
			<item value="18.287822536" age="227"/>
			<item value="18.3245866" age="228"/>
			<item value="18.360795645" age="229"/>
			<item value="18.396431373" age="230"/>
			<item value="18.431475639" age="231"/>
			<item value="18.465909907" age="232"/>
			<item value="18.499715238" age="233"/>
			<item value="18.532872277" age="234"/>
			<item value="18.565361241" age="235"/>
			<item value="18.597160159" age="236"/>
			<item value="18.628251422" age="237"/>
			<item value="18.658612451" age="238"/>
			<item value="18.688221612" age="239"/>
			<item value="18.717056794" age="240"/>
		</percentile>
		<percentile displayValue="5th" value="5">
			<item value="14.719292573" age="24"/>
			<item value="14.683608414" age="25"/>
			<item value="14.648433294" age="26"/>
			<item value="14.613786255" age="27"/>
			<item value="14.579685777" age="28"/>
			<item value="14.546149661" age="29"/>
